<?php
/**
 * PostFinance Checkout Magento 2
 *
 * This Magento 2 extension enables to process payments with PostFinance Checkout (https://www.postfinance.ch/checkout/).
 *
 * @package PostFinanceCheckout_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */

/** @var $block \PostFinanceCheckout\Payment\Block\DeviceSession */
?>
<script type="text/x-magento-init">
{
    "*": {
        "PostFinanceCheckout_Payment/js/postfinancecheckout-device": {
            "scriptUrl" : "<?=$block->escapeHtml($block->getScriptUrl())?>",
            "identifierUrl" : "<?=$block->escapeHtml($block->getSessionIdentifierUrl())?>"
        }
    }
}
</script>