<?php
/**
 * PostFinance Checkout Magento 2
 *
 * This Magento 2 extension enables to process payments with PostFinance Checkout (https://www.postfinance.ch/).
 *
 * @package PostFinanceCheckout_Payment
 * @author customweb GmbH (http://www.customweb.com/)
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache Software License (ASL 2.0)
 */
/**
 * @formatter:off
 */

/** @var $block \PostFinanceCheckout\Payment\Block\Adminhtml\Sales\Order\View */
?>

<?php if ($block->hasPendingRefund()) : ?>
	<div class="messages">
		<div class="message message-warning warning">
			<?=$block->escapeHtml(\__('This order has a pending refund request.'))?>
			<a class="message-link" href="<?=$block->escapeHtml($block->getRefundUrl())?>"><?=$block->escapeHtml(\__('Send Refund Request'))?></a>
		</div>
	</div>
<?php endif; ?>